config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from django.utils.translation import gettext_lazy as _


from core.views import (
    selectlanguage,
    )


urlpatterns = [
    path('selectlanguage/',selectlanguage,name='selectlanguage'),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns (
    path(
        _("about/"), TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # Core
    path("", include("core.urls", namespace="core")),


    # Content
    path(_("courses/"), include("content.urls", namespace="content")),
    # path("payment/", include("payment.urls", namespace="payment")),

    # tailwind
    path("__reload__/", include("django_browser_reload.urls")),
    
    # ckeditor 
    path('_ckeditor/', include('ckeditor_uploader.urls')),

    # translation
    path(_('rosetta/'), include('rosetta.urls')),

    # User management
    path(_("users/"), include("users.urls", namespace="users")),
    path(_("accounts/"), include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(_('staff/'), include('staff.urls', namespace='staff')),
    prefix_default_language=False,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, VideoDetailView
from content import views
from django.utils.translation import gettext_lazy as _
# from mysite.core import views

app_name = "content"  

urlpatterns = [
    path('product-chart/', views.product_chart, name='product-chart'),
    path(_('remove-from-saved/<pk>/'),
         views.RemoveFromSavedView.as_view(), name='remove-from-saved'),
    path('', CourseListView, name='course-list'),
    path("<slug>/", CourseDetailView.as_view(), name='course-detail'),
    path(_('saved-product/'), views.SavedProductView.as_view(), name='saved-product'),
    path("<slug>/<video_slug>/", VideoDetailView.as_view(), name='video-detail'),
    
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from core import views

 
app_name = "core"

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path('', views.home, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('price/', views.price, name='price'),
    path('blog/', views.blog, name='blog'),
    path('affiliate/', views.affiliate, name='affiliate'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

templates/pages/about.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "About us" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="mt-6 text-2xl  text-center dark:text-white text-gray-900">
              {% trans "About us" %}
          </h2>
            <div class="dark:text-white text-gray-900">
                {{ privacytermsabout.about_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/affiliate.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Affiliate" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="my-4 text-2xl font-extrabold dark:text-white text-gray-900 text-center">
              {% trans "Affiliate" %}
          </h2>
          <div class="dark:text-white text-gray-900 text-center">
                {{ affiliate.affiliate_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/base.html
{% load static i18n %}
{% load i18n %}
{% load static tailwind_tags %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}djvideomem{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This is a video membership site built with Django">
    <meta name="author" content="Matthew Freire">
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    {% block css %}
      <link href="{% static 'css/flowbite.min.css' %}" rel="stylesheet" />
     {% tailwind_css %}

     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    {% endblock %}
     
    <script>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark');
      } else {
          document.documentElement.classList.remove('dark')
      }
    </script>
    <script src="{% static '/js/flowbite.min.js' %}"></script>
  </head>

  <body class="bg-white dark:bg-gray-900">

    {% include 'pages/navbar.html' %}

    {% if messages %}
    {% for message in messages %}
        <div class="mx-auto max-w-screen-sm px-2">
        <section class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            <div class="relative items-center w-full px-5 mx-auto md:px-12 lg:px-24 max-w-7xl">
            <div id="toast-success" class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
                <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Check icon</span>
                </div>
                <div class="ml-3 text-lg font-normal dark:text-white text-gray-900">
                    {{ message }}
                </div>
                <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-white dark:hover:text-gray-500 dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-success" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </button>
            </div>
            </div>
        </section>
        </div>
    {% endfor %}
    {% endif %}

    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
      {% include 'pages/footer.html' %}
    <script>
        var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
        var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');
        
        // Change the icons inside the button based on previous settings
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            themeToggleLightIcon.classList.remove('hidden');
        } else {
            themeToggleDarkIcon.classList.remove('hidden');
        }
        
        var themeToggleBtn = document.getElementById('theme-toggle');
        
        themeToggleBtn.addEventListener('click', function() {
        
            // toggle icons inside button
            themeToggleDarkIcon.classList.toggle('hidden');
            themeToggleLightIcon.classList.toggle('hidden');
        
            // if set via local storage previously
            if (localStorage.getItem('color-theme')) {
                if (localStorage.getItem('color-theme') === 'light') {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                } else {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                }
        
            // if NOT set via local storage previously
            } else {
                if (document.documentElement.classList.contains('dark')) {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                } else {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                }
            }
            
        });

      </script>
      {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script> {% endcomment %}
      <script src="{% static '/js/flowbite.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>
 

templates/pages/blog.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Blog" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="mt-6 text-2xl font-extrabold dark:text-white text-gray-900">
              {% trans "Blog" %}
          </h2>
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/contact.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Contact" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

<div class="flex items-center justify-center mb-4 px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-md">
      <div>
          <h2 class="mt-6 text-2xl font-extrabold text-center dark:text-white text-gray-900">
              {% trans "Get in touch" %}
          </h2>
      </div>
      <form class="my-6" id="signup_form" method="post">
        {% csrf_token %}
  
        {{ form|crispy }}       
        <div>
            <button type="submit"
                    class="relative flex justify-center w-full px-4 py-2 text-lg font-medium text-white bg-green-500 border border-transparent border-solid rounded-md group hover:bg-green-700">
                <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                    <svg class="w-5 h-5 text-white-500 group-hover:text-white-400"
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                          aria-hidden="true">
                        <path fill-rule="evenodd"
                              d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                </span>
                {% trans "Submit message" %}
            </button>
        </div>
      </form>
    </div>
</div>
{% endblock content %}

templates/pages/faq.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Faq" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="mt-6 text-2xl font-extrabold dark:text-white text-gray-900">
              {% trans "Frequently asked questions" %}
          </h2>
            <p class="my-4 text-lg dark:text-white text-gray-900">Updated : {{ faq.last_update|timesince}} ago</p>
            
            <div class="dark:text-white text-gray-900">
                {{ faq.faq_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/footer.html
{% load static i18n %}

    <footer class="text-center text-gray-700 dark:text-white lg:text-left mt-6">
        <div class="bg-gray-100 dark:bg-gray-800/50 mt-2">
            <div class="container mx-auto">
                <div class="grid-1 grid gap-8 md:grid-cols-2  py-4">
                    <div class="md:py-2 text-center md:text-left">
                      <span class="text-gray-700 dark:text-white">{% translate "© 2023 Copyright:" %}</span>
                      <a
                        class="font-semibold text-gray-700 dark:text-white dark:hover:text-gray-100 hover:text-gray-500 transition-colors duration-300"
                        href="https://mdbootstrap.com/"
                        >realadsnow.com</a
                      >
                    </div>
                    <div class="flex items-center justify-center md:justify-end md:py-2">
                        <div class="mr-12">
                          <a href="{% url 'core:terms' %}" class="text-gray-700 dark:text-white dark:hover:text-gray-100 hover:text-gray-500 transition-colors duration-300">{% translate "Terms of Use" %}</a>
                        </div>
                        <div class="mr-12">
                          <a href="{% url 'core:privacy' %}" class="text-gray-700 dark:text-white dark:hover:text-gray-100 hover:text-gray-500 transition-colors duration-300">{% translate "Privacy" %}</a>
                        </div>
                        <div class="mr-12">
                          <a href="{% url 'core:contact' %}" class="text-gray-700 dark:text-white dark:hover:text-gray-100 hover:text-gray-500 transition-colors duration-300">{% translate "Faq" %}</a>
                        </div>
                        <div class="mr-12">
                        <span>{% translate "Find us on:" %}</span>
                        </div>
                        <div class="flex justify-center">
                            <a href="#!" class="mr-6 text-gray-700 dark:text-white">
                            <svg
                            aria-hidden="true"
                            focusable="false"
                            data-prefix="fab"
                            data-icon="facebook-f"
                            class="svg-inline--fa fa-facebook-f w-2.5"
                            role="img"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 320 512">
                            <path
                              fill="currentColor"
                              d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path>
                            </svg>
                            </a>
                            <a href="#!" class="mr-6 text-gray-700 dark:text-white">
                            <svg
                            aria-hidden="true"
                            focusable="false"
                            data-prefix="fab"
                            data-icon="twitter"
                            class="svg-inline--fa fa-twitter w-4"
                            role="img"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 512 512">
                            <path
                              fill="currentColor"
                              d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path>
                            </svg>
                            </a>
                            <a href="#!" class="mr-6 text-gray-700 dark:text-white">
                            <svg
                            aria-hidden="true"
                            focusable="false"
                            data-prefix="fab"
                            data-icon="instagram"
                            class="svg-inline--fa fa-instagram w-3.5"
                            role="img"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 448 512">
                            <path
                              fill="currentColor"
                              d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path>
                            </svg>
                            </a>
                        </div>
                    </div>  
                </div>
            </div> 
        </div>
    </footer>

templates/pages/home.html
{% extends "pages/base.html" %}
{% load static i18n %}

{% block content %}
<section>
    <div class="relative items-center w-full px-5 py-12 mx-auto md:px-12 lg:px-16 max-w-7xl lg:py-24">
      <div class="flex w-full mx-auto text-left">
        <div class="relative inline-flex items-center mx-auto align-middle">
          <div class="text-center">
            <h1 class="text-4xl font-medium leading-none tracking-tighter text-gray-700 dark:text-white">
              {% translate "Your perfect" %}<br class="hidden lg:block">
              {% translate "Hand Picked Winning Products" %} 
            </h1>
            <p class="max-w-xl mx-auto mt-8 text-base leading-relaxed text-gray-700 dark:text-white">{% translate "We analyze hundreds of thousands of examples of  ads and discover the most viral products and videos every day" %}</p>
            <div class="flex justify-center w-full max-w-2xl gap-2 mx-auto mt-6">
              {% if user.is_authenticated %}
              <div class="mt-3 rounded-lg sm:mt-0">
                <a href="{% url 'content:course-list' %}"  class="text-white bg-gray-700 hover:bg-gray-500 font-medium rounded-full text-lg px-5 py-2 text-center mr-3 md:mr-0  dark:hover:bg-gray-700 hidden lg:block">
                  {% trans "Browse Produits" %}
                </a>
              </div>
              {% else %}
              <div class="mt-3 rounded-lg sm:mt-0">
                <a href="{% url 'account_login' %}"  class="text-gray-700 dark:text-white hover:bg-gray-500 hover:text-white font-medium rounded-full text-lg px-5 py-2 text-center mr-3 md:mr-0 hidden lg:block">
                  {% trans "Login" %}
                </a>
              </div>
              <div class="mt-3 rounded-lg sm:mt-0 sm:ml-3">
                <a href="{% url 'account_signup' %}" class="text-white bg-gray-700 hover:bg-gray-500 font-medium rounded-full text-lg px-5 py-2 text-center mr-3 md:mr-0  dark:hover:bg-gray-700 hidden lg:block">
                  {% trans "Sign Up" %}
                </a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
     </div>
</section>
 
{% endblock content %}

templates/pages/price.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Price" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


  <div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="my-4 text-2xl font-extrabold dark:text-white text-gray-900 text-center">
              {% trans "Choose your plan" %}
          </h2>
          <div class="dark:text-white text-gray-900 text-center">
                {{ price.price_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/privacy.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Privacy Policy" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="mt-6 text-2xl dark:text-white text-gray-900">
              {% trans "Privacy Policy Notice" %}
          </h2>
            <p class="my-4 text-lg dark:text-white text-gray-900">Updated : {{ privacy.last_update|timesince}} ago</p>
            
            <div class="dark:text-white text-gray-900">
                {{ privacy.privacy_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}

templates/pages/terms.html
{% extends "pages/base.html" %}
{% load i18n %}
{% block head_title %}{% trans "Terms" %}{% endblock %}
{% load crispy_forms_tags %}

{% block content %}


<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="w-full max-w-4xl space-y-8">
      <div>
          <h2 class="mt-6 text-2xl dark:text-white text-gray-900">
              {% trans "Terms and Conditions" %}
          </h2>
            <p class="my-4 text-lg dark:text-white text-gray-900">Updated : {{ terms.last_update|timesince}} ago</p>
            
            <div class="dark:text-white text-gray-900">
                {{ terms.terms_text|safe}}
            </div> 
       </div>
      
    </div>
  </div>
{% endblock content %}