config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from django.utils.translation import gettext_lazy as _


from core.views import (
    selectlanguage,
    )


urlpatterns = [
    path('selectlanguage/',selectlanguage,name='selectlanguage'),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns (
    path(
        _("about/"), TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # Core
    path("", include("core.urls", namespace="core")),


    # Content
    path(_("courses/"), include("content.urls", namespace="content")),
    # path("payment/", include("payment.urls", namespace="payment")),

    # tailwind
    path("__reload__/", include("django_browser_reload.urls")),
    
    # ckeditor 
    path('_ckeditor/', include('ckeditor_uploader.urls')),

    # translation
    path(_('rosetta/'), include('rosetta.urls')),

    # User management
    path(_("users/"), include("users.urls", namespace="users")),
    path(_("accounts/"), include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(_('staff/'), include('staff.urls', namespace='staff')),
    prefix_default_language=False,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, VideoDetailView
from content import views
from django.utils.translation import gettext_lazy as _
# from mysite.core import views

app_name = "content"  

urlpatterns = [
    path('product-chart/', views.product_chart, name='product-chart'),
    path(_('remove-from-saved/<pk>/'),
         views.RemoveFromSavedView.as_view(), name='remove-from-saved'),
    path('', CourseListView, name='course-list'),
    path("<slug>/", CourseDetailView.as_view(), name='course-detail'),
    path(_('saved-product/'), views.SavedProductView.as_view(), name='saved-product'),
    path("<slug>/<video_slug>/", VideoDetailView.as_view(), name='video-detail'),
    
]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from core import views

 
app_name = "core"

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path('', views.home, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('price/', views.price, name='price'),
    path('blog/', views.blog, name='blog'),
    path('affiliate/', views.affiliate, name='affiliate'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

content/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import (
    OrderItem, Course
)



class AddToCartForm(forms.ModelForm):
    # quantity = forms.IntegerField(min_value=1, initial=1, label=_('Quantity'))

    class Meta:
        model = OrderItem
        fields = ['quantity']

    def __init__(self, *args, **kwargs):
        self.course_id = kwargs.pop('course_id')
        course = Course.objects.get(id=self.course_id)
        super().__init__(*args, **kwargs)

content/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, reverse, redirect, render
from .models import Course, Video, OrderItem, Category, Technology, Country,Language, Button, City
from .mixins import CoursePermissionMixin
from django.core.mail import send_mail
from .forms import AddToCartForm
from django.conf import settings
from django.contrib import messages
from django.utils.translation import gettext as _
from .utils import get_or_set_order_session
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from parler.views import TranslatableSlugMixin
from django.db.models import F
from django.shortcuts import render
from django.db.models import Sum
from django.http import JsonResponse
from django.db.models import Count


def is_valid_queryparam(param):
    return param != '' and param is not None


def CourseListView(request):
    qs = Course.objects.all()
    product_count = qs.count()
    

    categories = Category.objects.all()
    technologies = Technology.objects.all()
    countries = Country.objects.all()
    languages = Language.objects.all()
    buttons = Button.objects.all()
    
    category = request.GET.get('category')
    technology = request.GET.get('technology')
    country = request.GET.get('country')
    language = request.GET.get('language')
    button = request.GET.get('button')
    aliexpress_price_min = request.GET.get('aliexpress_price_min')
    aliexpress_price_max = request.GET.get('aliexpress_price_max')
    likes_count_min = request.GET.get('likes_count_min')
    likes_count_max = request.GET.get('likes_count_max')
    date_min = request.GET.get('date_min')
    date_max = request.GET.get('date_max')
    is_faceBook = request.GET.get('is_faceBook')
    is_pinterest = request.GET.get('is_pinterest')
    is_tiktok = request.GET.get('is_tiktok')
    has_video = request.GET.get('has_video')
    has_photo = request.GET.get('has_photo')
    

    if is_valid_queryparam(category) and category != 'All categories':
        # qs = qs.filter(categories__name=category)
        # qs = qs.filter(Q(categories__name=category) | Q(categories__name_fr=category))
        qs = qs.filter(categories__name__contains=category) | qs.filter(categories__name_fr__contains=category)


    if is_valid_queryparam(technology) and technology != 'Site type':
        qs = qs.filter(technologies__name=technology)

    if is_valid_queryparam(country) and country != 'Country':
        qs = qs.filter(countries__name=country)

    if is_valid_queryparam(language) and language != 'Language':
        qs = qs.filter(languages__name=language)

    if is_valid_queryparam(button) and button != 'Button':
        qs = qs.filter(buttons__name=button)

    if is_valid_queryparam(aliexpress_price_min):
        qs = qs.filter(aliexpress_price__gte=aliexpress_price_min)

    if is_valid_queryparam(aliexpress_price_max):
        qs = qs.filter(aliexpress_price__lt=aliexpress_price_max)

    if is_valid_queryparam(likes_count_min):
        qs = qs.filter(likes__gte=likes_count_min)

    if is_valid_queryparam(likes_count_max):
        qs = qs.filter(likes__lt=likes_count_max)

    if is_valid_queryparam(date_min):
        qs = qs.filter(ads_run_since__gte=date_min)

    if is_valid_queryparam(date_max):
        qs = qs.filter(ads_run_since__lt=date_max)

    if is_faceBook == 'on':
        qs = qs.filter(is_faceBook=True)

    if is_pinterest == 'on':
        qs = qs.filter(is_pinterest=True)

    if is_tiktok == 'on':
        qs = qs.filter(is_tiktok=True)

    if has_video == 'on':
        qs = qs.filter(has_video=True)

    if has_photo == 'on':
        qs = qs.filter(has_photo=True)

    page_num = request.GET.get('page', 1)

    paginator = Paginator(qs, 4) 

    try:
        qs = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        qs = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        qs = paginator.page(paginator.num_pages)

    context = {
        'queryset': qs,
        'categories': categories,
        'technologies': technologies,
        'countries': countries,
        'buttons': buttons,
        'languages': languages,
        'product_count': product_count,
    }
    return render(request, "content/course_list.html", context)



class CourseDetailView(TranslatableSlugMixin, DetailView):
    template_name = "content/course_detail.html"
    form_class = AddToCartForm
    


    def get_object(self):
            return get_object_or_404(Course, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("content:saved-product")
 
    
    


    def get_form_kwargs(self):
        kwargs = super(CourseDetailView, self).get_form_kwargs()
        kwargs["course_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        course = self.get_object()

        item_filter = order.items.filter(
            course=course
         )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.course = course
            new_item.order = order
            new_item.save()

        return super(CourseDetailView, self).form_valid(form)
   

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['course'] = self.get_object()
        return context


def product_chart(request):
    labels = []
    data = []

    queryset = City.objects.all()
    for city in queryset:
        labels.append(city.name)
        data.append(city.population)
    
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })


class VideoDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "content/video_detail.html"

    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        course = self.get_course()
        subscription = self.request.user.subscription
        pricing_tier = subscription.pricing
        context.update({
            "has_permission": pricing_tier in course.pricing_tiers.all()
        })
        return context

    def get_course(self):
        return get_object_or_404(Course, slug=self.kwargs["slug"])

    def get_object(self):
        video = get_object_or_404(Video, slug=self.kwargs["video_slug"])
        return video

    def get_queryset(self):
        course = self.get_course()
        return course.videos.all()


class SavedProductView(generic.TemplateView):
    template_name = "content/saved_product.html"

    def get_context_data(self, **kwargs):
        context = super(SavedProductView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class RemoveFromSavedView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("content:saved-product")

templates/content/saved_product.html
{% extends "pages/base.html" %}
{% load i18n %}
{% load cool_num %}

{% block content %}
<div class="  mx-auto max-w-screen-xl px-2">
       <p class='text-2xl font-bold text-gray-900 dark:text-white text-center'>
            {% trans "Saved Products" %}
        </p>
    {% if order.items.count > 0 %}
        <div class="mt-2 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2
            lg:grid-cols-3  xl:gap-x-8">
            {% for item in order.items.all %}
                <div class="group relative block overflow-hidden rounded-lg shadow-lg">
                    <div class="flex items-center justify-between p-3">
                        <div class="flex items-center space-x-2">
                            <div class="-space-y-1">
                                <h2 class="text-lg text-gray-900 dark:text-white">{{ item.course.name_of_store|title}}</h2>
                                <span class='text-base text-gray-900 dark:text-white'>Created : {{ item.course.ads_run_since|timesince}} ago</span>
                            </div>
                        </div>
                        
                        <div class="flex items-center space-x-3">
                             {% if item.course.is_faceBook %}
                                <button type="button" title="Like post" 
                                    class="flex     
                                    items-center justify-center dark:bg-white dark:text-blue-500 
                                    text-blue-500 hover:text-white hover:bg-blue-500 rounded-md">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-facebook " viewBox="0 0 16 16">
                                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                                    </svg>
                                </button>
                            {% endif %}
                            {% if item.course.is_tiktok %}
                                <button type="button" title="Like post" 
                                    class="flex items-center justify-center hover:bg-white hover:text-[#ff0050] text-white
                                    bg-[#ff0050] rounded-md">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
                                    <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3V0Z"/>
                                    </svg>
                                </button>
                            {% endif %}
                            {% if item.course.is_pinterest %}
                                <button type="button" title="Like post" 
                                    class="flex items-center justify-center
                                    bg-[#E60023]  text-white hover:text-[#E60023] hover:bg-white rounded-md">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-pinterest" viewBox="0 0 16 16">
                                    <path d="M8 0a8 8 0 0 0-2.915 15.452c-.07-.633-.134-1.606.027-2.297.146-.625.938-3.977.938-3.977s-.239-.479-.239-1.187c0-1.113.645-1.943 1.448-1.943.682 0 1.012.512 1.012 1.127 0 .686-.437 1.712-.663 2.663-.188.796.4 1.446 1.185 1.446 1.422 0 2.515-1.5 2.515-3.664 0-1.915-1.377-3.254-3.342-3.254-2.276 0-3.612 1.707-3.612 3.471 0 .688.265 1.425.595 1.826a.24.24 0 0 1 .056.23c-.061.252-.196.796-.222.907-.035.146-.116.177-.268.107-1-.465-1.624-1.926-1.624-3.1 0-2.523 1.834-4.84 5.286-4.84 2.775 0 4.932 1.977 4.932 4.62 0 2.757-1.739 4.976-4.151 4.976-.811 0-1.573-.421-1.834-.919l-.498 1.902c-.181.695-.669 1.566-.995 2.097A8 8 0 1 0 8 0z"/>
                                    </svg>
                                </button>
                            {% endif %}
                        </div>
                    </div>
                    <div class="p-3 flex items-center justify-center">
                        {% if course.has_video %}
                            <button
                                class="absolute bg-gray-800 bg-opacity-30 hover:bg-opacity-30 p-4 rounded-full text-white hover:bg-white hover:text-gray-800">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-play-fill" viewBox="0 0 16 16">
                                    <path d="m11.596 8.697-6.363 3.692c-.54.313-1.233-.066-1.233-.697V4.308c0-.63.692-1.01 1.233-.696l6.363 3.692a.802.802 0 0 1 0 1.393z"/>
                                </svg>
                            </button>
                        {% endif %}
                        <img
                        src="{{ item.course.product_thumbnail.url }}"
                        alt=""
                        class="aspect-square rounded-lg  w-full object-cover"
                        />
                         {% comment %} {% video course.product_video 'tiny' %} {% endcomment %}
                    </div>
                    <div class="relative px-3 text-center ">
                        <a class="" href="{{ item.course.get_absolute_url }}">
                            <h1 class="text-lg font-medium text-gray-900 dark:text-white mt-2">
                                {{ item.course.name_of_product|title|truncatechars:26  }}
                            </h1>
                        </a>
                        <div class="grid grid-cols-3 text-gray-900 dark:text-white gap-2 ">
                            <div class="flex flex-col justify-start p-2">
                                <p class="flex mx-auto text-lg font-medium">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-hand-thumbs-up-fill mr-2" viewBox="0 0 16 16">
                                        <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>
                                    {{ item.course.likes|cool_num }}
                                </p>
                            </div>
                            <div class="flex flex-col justify-start p-2">
                                <p class="flex mx-auto text-lg font-medium">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chat-dots-fill mr-2" viewBox="0 0 16 16">
                                        <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM5 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                      </svg>
                                    {{ item.course.comment|cool_num }}
                                 </p>
                            </div>
                            <div class="flex mx-auto flex-col justify-start p-2">
                                <p class="flex text-lg font-medium">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-eye-fill mr-2" viewBox="0 0 16 16">
                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                      </svg>
                                    {{ item.course.views|cool_num }}
                                </p>
                            </div>
                        </div>
                        <a   href="{% url 'content:remove-from-saved' item.id %}">
                            <button type="button" class="text-white  
                                font-medium rounded-lg text-lg px-5 py-2.5 text-center inline-flex items-center mr-2  border-4  border-red-600  bg-red-600 hover:bg-red-700   text-lg my-2">
                               
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash-fill text-white mr-2" viewBox="0 0 16 16">
                                  <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                </svg>
                                    Remove
                            </button>
                        </a>
          
                   
                    
                    </div>
                </div> 
            {% endfor %}  
        </div>
    {% else %}
        <p class='text-2xl text-gray-900 dark:text-white text-center'>
            {% trans "There are no saved products in your list." %}
            <a class='text-green-500 underline underline-offset-8' href="{% url 'content:course-list' %}">
                    {% trans "Continue to our listings" %}
            </a>
        </p>
    {% endif %}
</div>
{% endblock content %}

templates/content/video_detail.html
{% extends "pages/base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
    <div class="py-16 flex flex-wrap">
        <div class="flex flex-wrap w-full">
        <div class="hidden md:block md:w-1/4 md:pr-10 md:py-6">
            {% for video in video.course.videos.all %}
                {% include 'content/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
        <div class="md:w-3/4 md:mt-0">
            {% if has_permission %}
            <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
            {% else %}
            <p>You do not have permission to view this course. Upgrade your subscription to start</p>
            {% endif %}
        </div>
        <div class="block md:hidden w-full mt-5 py-5">
            {% for video in video.course.videos.all %}
                {% include 'content/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
    </div>
    </section>
{% endblock content %}